/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chem;

import chem.atoms.Sodium;

/**
 *
 * @author U AMD
 */
public class AtomInput extends javax.swing.JFrame {

    /**
     * Creates new form atomInput
     */
    private static GUI gui; // GUI

    public AtomInput(GUI gui) {
        this.gui = gui; // init
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        attributeWrap = new javax.swing.JPanel();
        lblType = new javax.swing.JLabel();
        atomType = new javax.swing.JComboBox();
        submit = new javax.swing.JButton();
        dynamicWarning = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        lblBondType = new javax.swing.JLabel();
        bondType = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atom Input");

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Atom Input");

        lblType.setText("Atom Type:");

        atomType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carbon", "Chlorine", "Fluorine", "Helium", "Hydrogen", "Lithium", "Nitrogen", "Oxygen", "Sodium" }));
        atomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atomTypeActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        lblBondType.setText("Bond Type:");

        bondType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Covalent", "Double", "Ionic" }));

        javax.swing.GroupLayout attributeWrapLayout = new javax.swing.GroupLayout(attributeWrap);
        attributeWrap.setLayout(attributeWrapLayout);
        attributeWrapLayout.setHorizontalGroup(
            attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributeWrapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attributeWrapLayout.createSequentialGroup()
                        .addGroup(attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dynamicWarning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(attributeWrapLayout.createSequentialGroup()
                                .addGap(0, 63, Short.MAX_VALUE)
                                .addComponent(cancel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attributeWrapLayout.createSequentialGroup()
                        .addGroup(attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblType)
                            .addComponent(lblBondType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(atomType, 0, 100, Short.MAX_VALUE)
                            .addComponent(bondType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        attributeWrapLayout.setVerticalGroup(
            attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributeWrapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(atomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBondType)
                    .addComponent(bondType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dynamicWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(attributeWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attributeWrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeWrap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    }//GEN-LAST:event_submitActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        String core = String.valueOf(atomType.getSelectedItem());
        String bondStr = String.valueOf(bondType.getSelectedItem());

        Atom atom = new Hydrogen(); // failsafe

        if (core.equals("Carbon")) {
            atom = new Carbon();
        } else if (core.equals("Chlorine")) {
            atom = new Chlorine();
        } else if (core.equals("Fluorine")) {
            atom = new Fluorine();
        } else if (core.equals("Helium")) {
            atom = new Helium();
        } else if (core.equals("Hydrogen")) {
            atom = new Hydrogen();
        } else if (core.equals("Lithium")) {
            atom = new Lithium();
        } else if (core.equals("Nitrogen")) {
            atom = new Nitrogen();
        } else if (core.equals("Oxygen")) {
            atom = new Oxygen();
        } else if (core.equals("Sodium")) {
            atom = new Sodium();
        }


        Molecule mol = gui.getMol();

        if (bondStr.equals("Covalent")) {
            if (mol.canCovalantBond(atom)) {
                gui.addToMol(atom, bondStr);
                this.dispose(); // close window
            } else {
                dynamicWarning.setText("Cannot Covalent Bond");
            }
        } else if (bondStr.equals("Double")){
            if (mol.canDoubleBond(atom)) {
                gui.addToMol(atom, bondStr);
                this.dispose(); // close window
            } else {
                dynamicWarning.setText("Cannot Double Bond");
            }
        } else {
            
            if (mol.canIonicBond(atom)) {
                gui.addToMol(atom, bondStr);
                this.dispose(); // close window
            } else {
                dynamicWarning.setText("Cannot Ionic Bond");
            }
        }


    }//GEN-LAST:event_submitMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void atomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atomTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtomInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtomInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtomInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtomInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtomInput(gui).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox atomType;
    private javax.swing.JPanel attributeWrap;
    private javax.swing.JComboBox bondType;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel dynamicWarning;
    private javax.swing.JLabel lblBondType;
    private javax.swing.JLabel lblType;
    private javax.swing.JButton submit;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
