/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chem;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author U AMD
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private static Molecule mol;

    public GUI(Molecule mol) {
        this.mol = mol;
        initComponents();
        this.setBackground(Color.white);
    }

    public GUI() {
        this.mol = new Molecule(new Hydrogen(), "None");
        initComponents();
        //MoleculeInput moleIn = new MoleculeInput(this); // launches before main GUI can run
        //moleIn.main(null);

        refresh();
    }

    public void addToMol(Atom atom, String bondType) {
        if (bondType.equals("Covalent")) {
            mol.covalentBond(atom);
        } else if (bondType.equals("Double")) {
            mol.doubleBond(atom);
        } else {
            mol.ionicBond(atom);
        }
        refresh();
    }

    public Molecule getMol() {
        return mol;
    }

    public void setMol(Molecule mol) {
        this.mol = mol;
        refresh();
    }

    private void reRender() {
        render.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        render.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(infoWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(render, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(render, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(infoWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap()));


    }

    private void refresh() {
        // update molecule
        // refreshes all
        this.remove(render);
        render = new Render(mol);
        this.add(render);
        reRender();
        this.invalidate();
        render.repaint();
        this.revalidate();

        molName.setText(mol.getName());
        molFormula.setText(mol.calculateFormula());
        molAtoms.setText(String.valueOf(mol.getNumberOfAtoms()));
        molProt.setText(String.valueOf(mol.getSize()));
        molFree.setText(String.valueOf(mol.getTotalFreeElectrons()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        render = new Render(mol);
        title = new javax.swing.JLabel();
        infoWrap = new javax.swing.JPanel();
        projectInfoWrap = new javax.swing.JPanel();
        lnlProjInfo = new javax.swing.JLabel();
        lblProjName = new javax.swing.JLabel();
        lblFP = new javax.swing.JLabel();
        projectName = new javax.swing.JLabel();
        filePath = new javax.swing.JLabel();
        moleculeInfoWrap = new javax.swing.JPanel();
        lblinfo = new javax.swing.JLabel();
        lblMolname = new javax.swing.JLabel();
        molName = new javax.swing.JLabel();
        lblFormula = new javax.swing.JLabel();
        molFormula = new javax.swing.JLabel();
        lblnoofAtom = new javax.swing.JLabel();
        molAtoms = new javax.swing.JLabel();
        lblnoofProt = new javax.swing.JLabel();
        molProt = new javax.swing.JLabel();
        lblFreeElc = new javax.swing.JLabel();
        molFree = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newProject = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        manualRefresh = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        deleteLast = new javax.swing.JMenuItem();
        project = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        molecule = new javax.swing.JMenu();
        newMolecule = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        addAtom = new javax.swing.JMenuItem();
        autoFill = new javax.swing.JMenu();
        autoHydrogen = new javax.swing.JMenuItem();
        autoFluorine = new javax.swing.JMenuItem();
        autoChlorine = new javax.swing.JMenuItem();
        buildInfo = new javax.swing.JMenu();
        showBuildInfo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chemical Render System");

        render.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        render.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout renderLayout = new javax.swing.GroupLayout(render);
        render.setLayout(renderLayout);
        renderLayout.setHorizontalGroup(
            renderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        renderLayout.setVerticalGroup(
            renderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        title.setFont(new java.awt.Font("Utsaah", 2, 24)); // NOI18N
        title.setText("Chemical Render System");

        projectInfoWrap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projectInfoWrap.setOpaque(false);
        projectInfoWrap.setPreferredSize(new java.awt.Dimension(255, 167));

        lnlProjInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnlProjInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnlProjInfo.setText("Project Info");

        lblProjName.setText("Project Name:");

        lblFP.setText("File Path:");

        projectName.setText("-");

        filePath.setText("-");

        javax.swing.GroupLayout projectInfoWrapLayout = new javax.swing.GroupLayout(projectInfoWrap);
        projectInfoWrap.setLayout(projectInfoWrapLayout);
        projectInfoWrapLayout.setHorizontalGroup(
            projectInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lnlProjInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(projectInfoWrapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projectInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProjName)
                    .addComponent(lblFP))
                .addGap(41, 41, 41)
                .addGroup(projectInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(projectName, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(filePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        projectInfoWrapLayout.setVerticalGroup(
            projectInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectInfoWrapLayout.createSequentialGroup()
                .addComponent(lnlProjInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(projectInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjName)
                    .addComponent(projectName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFP)
                    .addComponent(filePath))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        moleculeInfoWrap.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblinfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblinfo.setText("Molecule Info");

        lblMolname.setText("Molecule Name:");

        molName.setText("-");

        lblFormula.setText("Formula:");

        molFormula.setText("-");

        lblnoofAtom.setText("Number Of Atoms:");

        molAtoms.setText("-");

        lblnoofProt.setText("Number Of Protons:");

        molProt.setText("-");

        lblFreeElc.setText("Free Electrons:");

        molFree.setText("-");

        javax.swing.GroupLayout moleculeInfoWrapLayout = new javax.swing.GroupLayout(moleculeInfoWrap);
        moleculeInfoWrap.setLayout(moleculeInfoWrapLayout);
        moleculeInfoWrapLayout.setHorizontalGroup(
            moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(moleculeInfoWrapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMolname)
                    .addComponent(lblFormula)
                    .addComponent(lblnoofAtom)
                    .addComponent(lblnoofProt)
                    .addComponent(lblFreeElc))
                .addGap(26, 26, 26)
                .addGroup(moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(molFree, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(molProt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(molFormula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(molAtoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(molName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        moleculeInfoWrapLayout.setVerticalGroup(
            moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moleculeInfoWrapLayout.createSequentialGroup()
                .addComponent(lblinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMolname)
                    .addComponent(molName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormula)
                    .addComponent(molFormula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnoofAtom)
                    .addComponent(molAtoms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnoofProt)
                    .addComponent(molProt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moleculeInfoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFreeElc)
                    .addComponent(molFree, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout infoWrapLayout = new javax.swing.GroupLayout(infoWrap);
        infoWrap.setLayout(infoWrapLayout);
        infoWrapLayout.setHorizontalGroup(
            infoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoWrapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectInfoWrap, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(moleculeInfoWrap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        infoWrapLayout.setVerticalGroup(
            infoWrapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoWrapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectInfoWrap, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(moleculeInfoWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        file.setText("File");

        newProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newProject.setText("New Project");
        newProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectActionPerformed(evt);
            }
        });
        file.add(newProject);
        file.add(jSeparator1);

        manualRefresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        manualRefresh.setText("Refresh");
        manualRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualRefreshActionPerformed(evt);
            }
        });
        file.add(manualRefresh);

        menuBar.add(file);

        edit.setText("Edit");

        deleteLast.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        deleteLast.setText("Remove Last Atom");
        deleteLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLastActionPerformed(evt);
            }
        });
        edit.add(deleteLast);

        menuBar.add(edit);

        project.setText("Project");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Change Current Molecule");
        project.add(jMenuItem2);

        menuBar.add(project);

        molecule.setText("Molecule");

        newMolecule.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        newMolecule.setText("New Molecule");
        newMolecule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMoleculeActionPerformed(evt);
            }
        });
        molecule.add(newMolecule);
        molecule.add(jSeparator2);

        addAtom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        addAtom.setText("Add Atom");
        addAtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAtomActionPerformed(evt);
            }
        });
        molecule.add(addAtom);

        autoFill.setText("Auto Fill");

        autoHydrogen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        autoHydrogen.setText("Hydrogens");
        autoHydrogen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoHydrogenActionPerformed(evt);
            }
        });
        autoFill.add(autoHydrogen);

        autoFluorine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        autoFluorine.setText("Fluorines");
        autoFluorine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoFluorineActionPerformed(evt);
            }
        });
        autoFill.add(autoFluorine);

        autoChlorine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        autoChlorine.setText("Chlorines");
        autoChlorine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoChlorineActionPerformed(evt);
            }
        });
        autoFill.add(autoChlorine);

        molecule.add(autoFill);

        menuBar.add(molecule);

        buildInfo.setText("Build Info");
        buildInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildInfoActionPerformed(evt);
            }
        });

        showBuildInfo.setText("Show Build Info");
        showBuildInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBuildInfoActionPerformed(evt);
            }
        });
        buildInfo.add(showBuildInfo);

        jMenuItem1.setText("Show Changelog");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        buildInfo.add(jMenuItem1);

        menuBar.add(buildInfo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(infoWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(render, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(render, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(infoWrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAtomActionPerformed
        AtomInput atomIn = new AtomInput(this);
        atomIn.main(null);
        refresh(); // repaint
    }//GEN-LAST:event_addAtomActionPerformed

    private void newMoleculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMoleculeActionPerformed
        MoleculeInput moleIn = new MoleculeInput(this);
        moleIn.main(null);
        refresh(); // repaint
    }//GEN-LAST:event_newMoleculeActionPerformed

    private void manualRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_manualRefreshActionPerformed

    private void autoChlorineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoChlorineActionPerformed
        int total = mol.getTotalFreeElectrons();
        for (int i = 0; i < total; i++) {
            mol.covalentBond(new Chlorine());
            refresh();
        }
    }//GEN-LAST:event_autoChlorineActionPerformed

    private void autoHydrogenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoHydrogenActionPerformed
        int total = mol.getTotalFreeElectrons();
        for (int i = 0; i < total; i++) {
            mol.covalentBond(new Hydrogen());
            refresh();
        }
    }//GEN-LAST:event_autoHydrogenActionPerformed

    private void autoFluorineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoFluorineActionPerformed
        int total = mol.getTotalFreeElectrons();
        for (int i = 0; i < total; i++) {
            mol.covalentBond(new Fluorine());
            refresh();
        }
    }//GEN-LAST:event_autoFluorineActionPerformed

    private void deleteLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLastActionPerformed
        if (mol.getNumberOfAtoms() > 1) {
            ArrayList<Atom> atoms = mol.getAtoms();
            Atom toRemove = atoms.get(atoms.size() - 1);
            mol.unBondAtom(toRemove);
            refresh();
        }
    }//GEN-LAST:event_deleteLastActionPerformed

    private void buildInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildInfoActionPerformed
    }//GEN-LAST:event_buildInfoActionPerformed

    private void showBuildInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBuildInfoActionPerformed
        BuildInfo bi = new BuildInfo();
        bi.main(null);
    }//GEN-LAST:event_showBuildInfoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Changelog cl = new Changelog();
        cl.main(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void newProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectActionPerformed
        NewProject np = new NewProject();
        np.main(null);
    }//GEN-LAST:event_newProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAtom;
    private javax.swing.JMenuItem autoChlorine;
    private javax.swing.JMenu autoFill;
    private javax.swing.JMenuItem autoFluorine;
    private javax.swing.JMenuItem autoHydrogen;
    private javax.swing.JMenu buildInfo;
    private javax.swing.JMenuItem deleteLast;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JLabel filePath;
    private javax.swing.JPanel infoWrap;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblFP;
    private javax.swing.JLabel lblFormula;
    private javax.swing.JLabel lblFreeElc;
    private javax.swing.JLabel lblMolname;
    private javax.swing.JLabel lblProjName;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JLabel lblnoofAtom;
    private javax.swing.JLabel lblnoofProt;
    private javax.swing.JLabel lnlProjInfo;
    private javax.swing.JMenuItem manualRefresh;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel molAtoms;
    private javax.swing.JLabel molFormula;
    private javax.swing.JLabel molFree;
    private javax.swing.JLabel molName;
    private javax.swing.JLabel molProt;
    private javax.swing.JMenu molecule;
    private javax.swing.JPanel moleculeInfoWrap;
    private javax.swing.JMenuItem newMolecule;
    private javax.swing.JMenuItem newProject;
    private javax.swing.JMenu project;
    private javax.swing.JPanel projectInfoWrap;
    private javax.swing.JLabel projectName;
    private javax.swing.JPanel render;
    private javax.swing.JMenuItem showBuildInfo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
