/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chem;

import java.awt.Color;

/**
 *
 * @author U AMD
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private static Molecule mol;

    public GUI(Molecule mol) {
        this.mol = mol;
        initComponents();
        this.setBackground(Color.white);
    }

    public GUI() {
        this.mol = new Molecule(new Hydrogen(), "Empty");
        initComponents();
        MoleculeInput moleIn = new MoleculeInput(this); // launches before main GUI can run
        moleIn.main(null);

        refresh();
    }

    public void addToMol(Atom atom) {
        mol.covalentBond(atom);
        refresh();
    }

    public Molecule getMol() {
        return mol;
    }

    public void setMol(Molecule mol) {
        this.mol = mol;
        refresh();
    }

    private void reRender() {
        render.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        render.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout renderLayout = new javax.swing.GroupLayout(render);
        render.setLayout(renderLayout);
        renderLayout.setHorizontalGroup(
                renderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 494, Short.MAX_VALUE));
        renderLayout.setVerticalGroup(
                renderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 494, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(render, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(render, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap()));


    }

    private void refresh() {
        // update molecule
        // refreshes all
        this.remove(render);
        render = new Render(mol);
        this.add(render);
        reRender();
        this.invalidate();
        render.repaint();
        this.revalidate();

        molName.setText(mol.getName());
        molFormula.setText(mol.calculateFormula());
        molAtoms.setText(String.valueOf(mol.getNumberOfAtoms()));
        molProt.setText(String.valueOf(mol.getSize()));
        molFree.setText(String.valueOf(mol.getTotalFreeElectrons()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        render = new Render(mol);
        title = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        lblinfo = new javax.swing.JLabel();
        lblMolname = new javax.swing.JLabel();
        molName = new javax.swing.JLabel();
        lblFormula = new javax.swing.JLabel();
        molFormula = new javax.swing.JLabel();
        lblnoofAtom = new javax.swing.JLabel();
        molAtoms = new javax.swing.JLabel();
        lblnoofProt = new javax.swing.JLabel();
        molProt = new javax.swing.JLabel();
        lblFreeElc = new javax.swing.JLabel();
        molFree = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newMolecule = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        manualRefresh = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        molecule = new javax.swing.JMenu();
        addAtom = new javax.swing.JMenuItem();
        autoFill = new javax.swing.JMenu();
        autoHydrogen = new javax.swing.JMenuItem();
        autoFluorine = new javax.swing.JMenuItem();
        autoChlorine = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chemical Render System");

        render.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        render.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout renderLayout = new javax.swing.GroupLayout(render);
        render.setLayout(renderLayout);
        renderLayout.setHorizontalGroup(
            renderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        renderLayout.setVerticalGroup(
            renderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        title.setFont(new java.awt.Font("Utsaah", 2, 24)); // NOI18N
        title.setText("Chemical Render System");

        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)));

        lblinfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblinfo.setText("Info Panel");

        lblMolname.setText("Molecule Name:");

        molName.setText("-");

        lblFormula.setText("Formula:");

        molFormula.setText("-");

        lblnoofAtom.setText("Number Of Atoms:");

        molAtoms.setText("-");

        lblnoofProt.setText("Number Of Protons:");

        molProt.setText("-");

        lblFreeElc.setText("Free Electrons:");

        molFree.setText("-");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMolname)
                    .addComponent(lblFormula)
                    .addComponent(lblnoofAtom)
                    .addComponent(lblnoofProt)
                    .addComponent(lblFreeElc))
                .addGap(26, 26, 26)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(molFree, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(molProt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(molFormula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(molAtoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(molName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addComponent(lblinfo)
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMolname)
                    .addComponent(molName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormula)
                    .addComponent(molFormula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnoofAtom)
                    .addComponent(molAtoms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnoofProt)
                    .addComponent(molProt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFreeElc)
                    .addComponent(molFree, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        file.setText("File");

        newMolecule.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMolecule.setText("New");
        newMolecule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMoleculeActionPerformed(evt);
            }
        });
        file.add(newMolecule);
        file.add(jSeparator1);

        manualRefresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        manualRefresh.setText("Refresh");
        manualRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualRefreshActionPerformed(evt);
            }
        });
        file.add(manualRefresh);

        menuBar.add(file);

        edit.setText("Edit");
        menuBar.add(edit);

        molecule.setText("Molecule");

        addAtom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        addAtom.setText("Add Atom");
        addAtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAtomActionPerformed(evt);
            }
        });
        molecule.add(addAtom);

        autoFill.setText("Auto Fill");

        autoHydrogen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        autoHydrogen.setText("Hydrogens");
        autoHydrogen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoHydrogenActionPerformed(evt);
            }
        });
        autoFill.add(autoHydrogen);

        autoFluorine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        autoFluorine.setText("Fluorines");
        autoFluorine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoFluorineActionPerformed(evt);
            }
        });
        autoFill.add(autoFluorine);

        autoChlorine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        autoChlorine.setText("Chlorines");
        autoChlorine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoChlorineActionPerformed(evt);
            }
        });
        autoFill.add(autoChlorine);

        molecule.add(autoFill);

        menuBar.add(molecule);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(render, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(render, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAtomActionPerformed
        AtomInput atomIn = new AtomInput(this);
        atomIn.main(null);
        refresh(); // repaint
    }//GEN-LAST:event_addAtomActionPerformed

    private void newMoleculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMoleculeActionPerformed
        MoleculeInput moleIn = new MoleculeInput(this);
        moleIn.main(null);
        refresh(); // repaint
    }//GEN-LAST:event_newMoleculeActionPerformed

    private void manualRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_manualRefreshActionPerformed

    private void autoChlorineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoChlorineActionPerformed
        int total = mol.getTotalFreeElectrons();
        for (int i = 0; i < total; i++) {
            mol.covalentBond(new Chlorine());
            refresh();
        }
    }//GEN-LAST:event_autoChlorineActionPerformed

    private void autoHydrogenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoHydrogenActionPerformed
        int total = mol.getTotalFreeElectrons();
        for (int i = 0; i < total; i++) {
            mol.covalentBond(new Hydrogen());
            refresh();
        }
    }//GEN-LAST:event_autoHydrogenActionPerformed

    private void autoFluorineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoFluorineActionPerformed
        int total = mol.getTotalFreeElectrons();
        for (int i = 0; i < total; i++) {
            mol.covalentBond(new Fluorine());
            refresh();
        }
    }//GEN-LAST:event_autoFluorineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI(mol).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAtom;
    private javax.swing.JMenuItem autoChlorine;
    private javax.swing.JMenu autoFill;
    private javax.swing.JMenuItem autoFluorine;
    private javax.swing.JMenuItem autoHydrogen;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblFormula;
    private javax.swing.JLabel lblFreeElc;
    private javax.swing.JLabel lblMolname;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JLabel lblnoofAtom;
    private javax.swing.JLabel lblnoofProt;
    private javax.swing.JMenuItem manualRefresh;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel molAtoms;
    private javax.swing.JLabel molFormula;
    private javax.swing.JLabel molFree;
    private javax.swing.JLabel molName;
    private javax.swing.JLabel molProt;
    private javax.swing.JMenu molecule;
    private javax.swing.JMenuItem newMolecule;
    private javax.swing.JPanel render;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
